# Generated by Django 4.2.5 on 2023-10-29 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.profile')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.watch')),
            ],
        ),
    ]
